# Generated by Django 4.1.6 on 2023-02-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_status_created_alter_status_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
