# Generated by Django 4.1.6 on 2023-02-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_label_alter_task_options_task_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task_manager.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='labels_task_related', to='task_manager.label'),
        ),
    ]
