# Generated by Django 4.2.1 on 2023-05-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_rename_customuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
