# Generated by Django 4.1.6 on 2023-02-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_label_task_alter_task_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
    ]
