# Generated by Django 4.1.6 on 2023-02-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_remove_label_task_remove_task_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posrednk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_manager.label')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(through='task_manager.Posrednk', to='task_manager.label'),
        ),
    ]
